import path from 'node:path'
import fastify from 'fastify'
import fastifyStatic from '@fastify/static'

const HOST = '127.0.0.1'
const PORT = 8080

const app = fastify({
  logger: true
})

// Serve static assets generated by vite
app.register(fastifyStatic, {
  root: path.resolve(path.join('src', 'main', 'resources', 'public'))
})

// Serve static assets
app.register(fastifyStatic, {
  root: path.resolve(path.join('src', 'main', 'resources', 'static', 'images')),
  prefix: '/images/',
  decorateReply: false
})

// API
app.get('/api', () => {
  return { ok: true }
})

await app.listen({
  host: HOST,
  port: PORT
})
